version: '3.8'

networks:
  traefik-public:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
    driver_opts:
      com.docker.network.driver.mtu: ${NETWORK_MTU}

  nextcloud-internal-network:
    external: false
    driver_opts:
      com.docker.network.driver.mtu: ${NETWORK_MTU}

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: ${MARIADB_CONTAINER_NAME}
    networks:
      - nextcloud-internal-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EG=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./nextcloud_database/config:/config
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: ${NEXTCLOUD_CONTAINER_NAME}
    networks:
      - traefik-public
      - nextcloud-internal-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EG=${TIMEZONE}
    volumes:
      - ./nextcloud_data/config:/config
      - ./nextcloud_data/data:/data
    labels:
      traefik.docker.network: ${TRAEFIK_NETWORK_NAME}
      traefik.enable: "true"
      traefik.http.routers.nextcloud-http.entrypoints: http
      traefik.http.routers.nextcloud-http.middlewares: https-redirect
      traefik.http.routers.nextcloud-http.rule: Host(`${NEXTCLOUD_HOST}`)
      traefik.http.routers.nextcloud-http.service: nextcloud
      traefik.http.routers.nextcloud-https.entrypoints: https
      traefik.http.routers.nextcloud-https.rule: Host(`${NEXTCLOUD_HOST}`)
      traefik.http.routers.nextcloud-https.service: nextcloud
      traefik.http.routers.nextcloud-https.tls: "true"
      traefik.http.routers.nextcloud-https.tls.certresolver: le
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"
    restart: unless-stopped

